In [81]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [82]:
df=pd.read_csv('50_Startups.csv')

In [83]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [84]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [85]:
df.duplicated().any()

False

In [86]:
df=df.drop(columns='State')

In [87]:
df.head(2)

R&D Spend  Administration  Marketing Spend     Profit
0   165349.2       136897.80        471784.10  192261.83
1   162597.7       151377.59        443898.53  191792.06

In [88]:
df.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit'], dtype='object')

In [89]:
df=df.rename(columns={'R&D Spend':'RnD_Spend'})
df=df.rename(columns={'Marketing Spend':'Marketing_Spend'})

In [90]:
df

RnD_Spend  Administration  Marketing_Spend     Profit
0   165349.20       136897.80        471784.10  192261.83
1   162597.70       151377.59        443898.53  191792.06
2   153441.51       101145.55        407934.54  191050.39
3   144372.41       118671.85        383199.62  182901.99
4   142107.34        91391.77        366168.42  166187.94
5   131876.90        99814.71        362861.36  156991.12
6   134615.46       147198.87        127716.82  156122.51
7   130298.13       145530.06        323876.68  155752.60
8   120542.52       148718.95        311613.29  152211.77
9   123334.88       108679.17        304981.62  149759.96
10  101913.08       110594.11        229160.95  146121.95
11  100671.96        91790.61        249744.55  144259.40
12   93863.75       127320.38        249839.44  141585.52
13   91992.39       135495.07        252664.93  134307.35
14  119943.24       156547.42        256512.92  132602.65
15  114523.61       122616.84        261776.23  129917.04
16   78013.11       121597.55        264346.06  126992.93
17   94657.16       145077.58        282574.31  125370.37
18   91749.16       114175.79        294919.57  124266.90
19   86419.70       153514.11             0.00  122776.86
20   76253.86       113867.30        298664.47  118474.03
21   78389.47       153773.43        299737.29  111313.02
22   73994.56       122782.75        303319.26  110352.25
23   67532.53       105751.03        304768.73  108733.99
24   77044.01        99281.34        140574.81  108552.04
25   64664.71       139553.16        137962.62  107404.34
26   75328.87       144135.98        134050.07  105733.54
27   72107.60       127864.55        353183.81  105008.31
28   66051.52       182645.56        118148.20  103282.38
29   65605.48       153032.06        107138.38  101004.64
30   61994.48       115641.28         91131.24   99937.59
31   61136.38       152701.92         88218.23   97483.56
32   63408.86       129219.61         46085.25   97427.84
33   55493.95       103057.49        214634.81   96778.92
34   46426.07       157693.92        210797.67   96712.80
35   46014.02        85047.44        205517.64   96479.51
36   28663.76       127056.21        201126.82   90708.19
37   44069.95        51283.14        197029.42   89949.14
38   20229.59        65947.93        185265.10   81229.06
39   38558.51        82982.09        174999.30   81005.76
40   28754.33       118546.05        172795.67   78239.91
41   27892.92        84710.77        164470.71   77798.83
42   23640.93        96189.63        148001.11   71498.49
43   15505.73       127382.30         35534.17   69758.98
44   22177.74       154806.14         28334.72   65200.33
45    1000.23       124153.04          1903.93   64926.08
46    1315.46       115816.21        297114.46   49490.75
47       0.00       135426.92             0.00   42559.73
48     542.05        51743.15             0.00   35673.41
49       0.00       116983.80         45173.06   14681.40

In [91]:
X

RnD_Spend  Administration  Marketing_Spend
0   165349.20       136897.80        471784.10
1   162597.70       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41       118671.85        383199.62
4   142107.34        91391.77        366168.42
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [92]:
y

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [95]:
X=df.iloc[: , :-1]
y=df.iloc[: , -1]

In [96]:
from sklearn.model_selection import train_test_split

In [97]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33 , random_state=12)

In [98]:
# scaling

from sklearn.preprocessing import StandardScaler

In [99]:
X_train.shape , X_test.shape , y_train.shape , y_test.shape

((33, 3), (17, 3), (33,), (17,))

In [100]:
scaler=StandardScaler()

In [101]:
X_train_scaled =scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [102]:
X_train_scaled

array([[ 9.70748376e-01, -5.07695964e-01,  6.44521052e-01],
       [-4.59425420e-01, -7.96636675e-01, -5.63362045e-02],
       [-1.62930904e+00,  8.67073483e-01, -1.72134645e+00],
       [-2.17798968e-02, -2.41038671e-01,  5.95516329e-01],
       [ 1.53073490e-02,  1.56277422e-01,  3.29294349e-01],
       [-5.12252162e-03, -9.90721623e-01, -6.30849997e-01],
       [-1.13092793e+00, -1.14962801e+00, -5.73241142e-01],
       [-2.92568968e-01,  5.48032811e-01, -1.36384426e+00],
       [-6.59274500e-01, -1.72230954e+00, -1.27061831e-01],
       [-2.05636716e-01, -6.58195255e-01,  6.42869577e-01],
       [ 1.79845897e+00,  1.68689922e+00,  1.72215649e+00],
       [-3.22385912e-01, -1.49860404e-01, -1.01440405e+00],
       [ 1.36649590e+00, -1.39622638e+00,  1.11917215e+00],
       [-1.16177385e+00,  1.86311837e+00, -1.50154241e+00],
       [-8.16446211e-01, -1.82846352e+00, -3.63805110e-01],
       [ 3.04880897e-01, -2.25183034e-01,  5.66465604e-01],
       [-1.02313090e+00, -5.62273879e-04

In [103]:
X_test_scaled

array([[-0.23685831,  3.293997  , -0.80482241],
       [-1.60157746, -0.14086943,  0.58349227],
       [ 1.11754261,  1.38635036,  0.79109778],
       [-1.04129052, -1.73961357, -0.4454797 ],
       [-1.02504023,  0.4368393 , -0.16112322],
       [-0.2462614 ,  1.77193496, -0.8902301 ],
       [ 0.0232415 ,  1.81003958,  0.60383863],
       [-1.61788194, -3.43406924, -1.72134645],
       [ 0.19252905,  1.79671116, -1.72134645],
       [ 0.91188185,  1.55025157,  0.69596564],
       [ 0.36618527,  1.36309399,  0.47069836],
       [-1.20284335, -2.70397801, -0.28416909],
       [-0.70025799, -3.45771264, -0.19290843],
       [ 0.78499551,  0.20866645,  0.30935912],
       [-0.34047576,  1.75496657, -1.03700146],
       [ 0.89924826,  1.95261593,  0.26852947],
       [-0.04127987,  1.31469803, -0.68146508]])

In [105]:
from sklearn.linear_model import LinearRegression

In [106]:
regressor= LinearRegression()

In [107]:
regressor.fit(X_train_scaled , y_train)

LinearRegression()

In [108]:
regressor.intercept_

116313.15606060605

In [109]:
regressor.coef_

array([39858.50902586,   387.52895637,  2774.19889948])

In [110]:
y_pred_test=regressor.predict(X_test_scaled)

In [111]:
y_pred_test

array([105916.11890489,  54040.79900082, 163588.65196166,  72898.8683733 ,
        75178.88086505, 104714.54452004, 119616.13883869,  45720.63564337,
       119907.99694983, 155190.92134563, 132742.8040282 ,  66533.40229354,
        86526.78657166, 148540.99454497, 100545.5519582 , 153657.50014802,
       113286.76578528])

In [112]:
y_test

28    103282.38
46     49490.75
7     155752.60
41     77798.83
36     90708.19
29    101004.64
21    111313.02
48     35673.41
19    122776.86
8     152211.77
17    125370.37
38     81229.06
37     89949.14
15    129917.04
31     97483.56
14    132602.65
26    105733.54
Name: Profit, dtype: float64

In [113]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
print(mean_squared_error(y_test,y_pred_test))
print(mean_absolute_error(y_test,y_pred_test))
print(np.sqrt(mean_squared_error(y_test,y_pred_test)))

99622528.95131348
8184.814213318275
9981.108603322253


In [114]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred_test)
print(score)

0.8981437954576094


# hence we get an 89 % accuracy which pretty good

In [116]:
import pickle

In [117]:
pickle.dump(scaler,open('Scaler.pkl' , 'wb'))
pickle.dump(regressor,open('Regressor.pkl' , 'wb'))

In [118]:
df.to_csv('startup50.csv')